version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  reviewers:
  - alejandro5042
  ignore:
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.0
